### ISSUE TITLE
travis build issue. Cannot import models.backends.init

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#19]
travis-ci build log:
```
 pip install .

0.00s$ cd neuronunit/unit_test/

The command "cd neuronunit/unit_test/" exited with 0.

0.00s$ cd working

The command "cd working" exited with 0.

4.64s$ python small_test.py

/home/travis/miniconda/lib/python3.7/site-packages/sciunit/scores/collections.py:296: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version

  class ScorePanel(pd.Panel, SciUnit):

consider installing pynn a heavier backend

ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_r7zu3xpn.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_631aot8w.py Thanks! [brian2]

Traceback (most recent call last):

  File "small_test.py", line 25, in <module>

    from neuronunit.optimisation.optimization_management import dtc_to_rheo, mint_generic_model

  File "/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/optimisation/optimization_management.py", line 64, in <module>

    from neuronunit.models import ReducedModel

  File "/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/models/__init__.py", line 8, in <module>

    from . import backends  # Required to register backends

ImportError: cannot import name 'backends' from 'neuronunit.models' (/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/models/__init__.py)

The command "python small_test.py" exited with 1.

4.28s$ python edt.py

/home/travis/miniconda/lib/python3.7/site-packages/sciunit/scores/collections.py:296: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version

  class ScorePanel(pd.Panel, SciUnit):

consider installing pynn a heavier backend

ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_8y4e69rw.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_74_egomc.py Thanks! [brian2]

Traceback (most recent call last):

  File "edt.py", line 27, in <module>

    from neuronunit.optimisation.optimization_management import dtc_to_rheo, mint_generic_model

  File "/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/optimisation/optimization_management.py", line 64, in <module>

    from neuronunit.models import ReducedModel

  File "/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/models/__init__.py", line 8, in <module>

    from . import backends  # Required to register backends

ImportError: cannot import name 'backends' from 'neuronunit.models' (/home/travis/miniconda/lib/python3.7/site-packages/neuronunit/models/__init__.py)

The command "python edt.py" exited with 1.

0.36s$ jupyter nbconvert --execute examples/chapter3.ipynb

[NbConvertApp] WARNING | pattern 'examples/chapter3.ipynb' matched no files

This application is used to convert notebook files (*.ipynb) to various other

formats.
```

**Comment by rgerkin** [comment]
Is this still a bug?  If so, were you able to Docker-ify it?

**Comment by russelljjarvis** [comment]
Yes, still a bug. I think my docker build works. I have not had time to check travis.ci. I think it still for a non-substantial reason. It would be awesome if I could make my fork a pip installable package. This would facilitate more use of my fork.

**Comment by russelljjarvis** [comment]
This is my highest priority.
